# Generated by Django 5.2.4 on 2025-07-06 16:18

import django.core.validators
import django.db.models.deletion
import payments.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bot', '0001_initial'),
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('text', models.TextField(help_text='Текст рекламного сообщения для отправки пользователям', verbose_name='Текст сообщения')),
                ('image', models.ImageField(blank=True, help_text='Изображение для прикрепления к сообщению', null=True, upload_to='ads/', verbose_name='Изображение')),
                ('button_text', models.CharField(blank=True, help_text='Текст для inline кнопки (необязательно)', max_length=100, verbose_name='Текст кнопки')),
                ('button_url', models.URLField(blank=True, help_text='URL для inline кнопки (необязательно)', verbose_name='Ссылка кнопки')),
                ('target_all_users', models.BooleanField(default=True, verbose_name='Отправить всем пользователям')),
                ('target_active_only', models.BooleanField(default=True, help_text='Отправлять только пользователям, которые не заблокировали бота', verbose_name='Только активным пользователям')),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='Оставьте пустым для немедленной отправки', null=True, verbose_name='Запланированное время отправки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Отправлено')),
                ('success_count', models.PositiveIntegerField(default=0, verbose_name='Успешно отправлено')),
                ('failed_count', models.PositiveIntegerField(default=0, verbose_name='Не удалось отправить')),
            ],
            options={
                'verbose_name': 'Рекламное объявление',
                'verbose_name_plural': 'Рекламные объявления',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма оплаты')),
                ('receipt_file', models.FileField(help_text='Скриншот или PDF чека об оплате', upload_to=payments.models.receipt_upload_path, verbose_name='Файл чека')),
                ('status', models.CharField(choices=[('pending', 'Ожидает проверки'), ('approved', 'Подтвержден'), ('rejected', 'Отклонен'), ('cancelled', 'Отменен')], default='pending', max_length=20, verbose_name='Статус платежа')),
                ('comment', models.TextField(blank=True, help_text='Комментарий администратора', verbose_name='Комментарий')),
                ('user_comment', models.TextField(blank=True, help_text='Комментарий от пользователя при отправке чека', verbose_name='Комментарий пользователя')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата подтверждения')),
                ('link_sent', models.BooleanField(default=False, help_text='Была ли отправлена ссылка на группу пользователю', verbose_name='Ссылка отправлена')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Подтвержден администратором')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='courses.course', verbose_name='Курс')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.paymentmethod', verbose_name='Способ оплаты')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bot.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.CreateModel(
            name='PaymentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_notified', models.BooleanField(default=False, verbose_name='Админ уведомлен')),
                ('user_notified_approved', models.BooleanField(default=False, verbose_name='Пользователь уведомлен об одобрении')),
                ('user_notified_rejected', models.BooleanField(default=False, verbose_name='Пользователь уведомлен об отклонении')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='payments.payment', verbose_name='Платеж')),
            ],
            options={
                'verbose_name': 'Уведомление о платеже',
                'verbose_name_plural': 'Уведомления о платежах',
            },
        ),
    ]
