# Generated by Django 4.2.7 on 2025-07-07 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together=set(),
        ),
    ]
