# Generated by Django 4.2.7 on 2025-08-22 18:39

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_course_short_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['order', 'name_qr'], 'verbose_name': 'Kurs', 'verbose_name_plural': 'Kurslar'},
        ),
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'ordering': ['order', 'name_qr'], 'verbose_name': 'Tólem usılı', 'verbose_name_plural': 'Tólem usılları'},
        ),
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='name',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='instructions',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='name',
        ),
        migrations.AddField(
            model_name='course',
            name='description_qr',
            field=models.TextField(default='q', verbose_name='Sıpatlaması (Qaraqalpaqsha)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='description_uz',
            field=models.TextField(default='q', verbose_name="Tavsifi (O'zbekcha)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='name_qr',
            field=models.CharField(default=1, max_length=200, verbose_name='Atı (Qaraqalpaqsha)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='name_uz',
            field=models.CharField(default=1, max_length=200, verbose_name="Nomi (O'zbekcha)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='instructions_qr',
            field=models.TextField(blank=True, verbose_name='Instrukciya (Qaraqalpaqsha)'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='instructions_uz',
            field=models.TextField(blank=True, verbose_name="Instruksiya (O'zbekcha)"),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='name_qr',
            field=models.CharField(default=1, max_length=100, verbose_name='Atı (Qaraqalpaqsha)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='name_uz',
            field=models.CharField(default=1, max_length=100, verbose_name="Nomi (O'zbekcha)"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Jaratılǵan sáne'),
        ),
        migrations.AlterField(
            model_name='course',
            name='group_link',
            field=models.URLField(verbose_name='Gruppaǵa silteme'),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktiv'),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Usınıs etilgen'),
        ),
        migrations.AlterField(
            model_name='course',
            name='max_students',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Maks. student sanı'),
        ),
        migrations.AlterField(
            model_name='course',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Eski bahası'),
        ),
        migrations.AlterField(
            model_name='course',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Sıralaw tártibi'),
        ),
        migrations.AlterField(
            model_name='course',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/images/', verbose_name='Kurs súwreti'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Kurs bahası (sumda)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Bahası'),
        ),
        migrations.AlterField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Jańalanǵan sáne'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bank atı'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='card_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Karta nomeri'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='cardholder_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Qabıllawshı'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Jaratılǵan sáne'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktiv'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Sıralaw tártibi'),
        ),
    ]
