# Generated by Django 4.2.7 on 2025-08-22 23:11

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_options_alter_paymentmethod_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['order', 'name_qr'], 'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'ordering': ['order', 'name_qr'], 'verbose_name': 'Способ оплаты', 'verbose_name_plural': 'Способы оплаты'},
        ),
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description_qr',
            field=models.TextField(verbose_name='Описание (Каракалпакский)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description_uz',
            field=models.TextField(verbose_name='Описание (Узбекский)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='group_link',
            field=models.URLField(verbose_name='Ссылка на группу'),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Рекомендуемый'),
        ),
        migrations.AlterField(
            model_name='course',
            name='max_students',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Максимум студентов'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name_qr',
            field=models.CharField(max_length=200, verbose_name='Название (Каракалпакский)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name_uz',
            field=models.CharField(max_length=200, verbose_name='Название (Узбекский)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Старая цена'),
        ),
        migrations.AlterField(
            model_name='course',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки'),
        ),
        migrations.AlterField(
            model_name='course',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/images/', verbose_name='Изображение курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Цена курса в сумах', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название банка'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='card_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Номер карты'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='cardholder_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Получатель'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='instructions_qr',
            field=models.TextField(blank=True, verbose_name='Инструкция (Каракалпакский)'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='instructions_uz',
            field=models.TextField(blank=True, verbose_name='Инструкция (Узбекский)'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='name_qr',
            field=models.CharField(max_length=100, verbose_name='Название (Каракалпакский)'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='name_uz',
            field=models.CharField(max_length=100, verbose_name='Название (Узбекский)'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки'),
        ),
    ]
