# Generated by Django 5.2.4 on 2025-07-06 16:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(help_text='Уникальный идентификатор чата в Telegram', unique=True, verbose_name='Chat ID')),
                ('username', models.CharField(blank=True, help_text='Имя пользователя в Telegram (@username)', max_length=100, null=True, verbose_name='Username')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Фамилия')),
                ('phone', models.CharField(blank=True, help_text='Номер телефона пользователя', max_length=20, null=True, verbose_name='Телефон')),
                ('is_active', models.BooleanField(default=True, help_text='Может ли пользователь получать сообщения', verbose_name='Активен')),
                ('is_blocked', models.BooleanField(default=False, help_text='Заблокирован ли пользователь', verbose_name='Заблокирован')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Последняя активность')),
            ],
            options={
                'verbose_name': 'Пользователь Telegram',
                'verbose_name_plural': 'Пользователи Telegram',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_state', models.CharField(default='start', help_text='Текущее состояние пользователя в диалоге с ботом', max_length=50, verbose_name='Текущее состояние')),
                ('state_data', models.JSONField(blank=True, default=dict, help_text='Дополнительные данные для текущего состояния', verbose_name='Данные состояния')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='bot.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Состояние пользователя',
                'verbose_name_plural': 'Состояния пользователей',
            },
        ),
    ]
