# Generated by Django 4.2.7 on 2025-08-22 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Masalan: about, support', max_length=50, unique=True, verbose_name='Kalit')),
                ('title', models.CharField(max_length=100, verbose_name='Sarlavha')),
                ('content', models.TextField(help_text='HTML formatida yozish mumkin', verbose_name='Matn')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Info sahifa',
                'verbose_name_plural': 'Info sahifalar',
            },
        ),
    ]
