# Generated by Django 4.2.7 on 2025-08-22 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_infopage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infopage',
            name='title',
        ),
    ]
