# Generated by Django 4.2.7 on 2025-08-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_remove_infopage_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infopage',
            options={'verbose_name': 'Информационная страница', 'verbose_name_plural': 'Информационные страницы'},
        ),
        migrations.AlterField(
            model_name='infopage',
            name='content',
            field=models.TextField(help_text='Может быть написан в формате HTML', verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='infopage',
            name='key',
            field=models.CharField(help_text='Например: about, support', max_length=50, unique=True, verbose_name='Ключ'),
        ),
    ]
