# Generated by Django 4.2.7 on 2025-08-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_alter_infopage_options_alter_infopage_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='language',
            field=models.CharField(blank=True, choices=[('qr', 'Qaraqalpaq'), ('uz', 'Uzbek')], max_length=2, null=True),
        ),
    ]
