# Generated by Django 4.2.7 on 2025-08-22 18:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_telegramuser_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infopage',
            options={'verbose_name': 'Informaciya beti', 'verbose_name_plural': 'Informaciya betleri'},
        ),
        migrations.AlterModelOptions(
            name='telegramuser',
            options={'ordering': ['-created_at'], 'verbose_name': 'Telegram paydalanıwshısı', 'verbose_name_plural': 'Telegram paydalanıwshıları'},
        ),
        migrations.AlterModelOptions(
            name='userstate',
            options={'verbose_name': 'Paydalanıwshı jaǵdayı', 'verbose_name_plural': 'Paydalanıwshılar jaǵdayları'},
        ),
        migrations.RemoveField(
            model_name='infopage',
            name='content',
        ),
        migrations.AddField(
            model_name='infopage',
            name='content_qr',
            field=models.TextField(default=1, help_text='HTML formatta jazıw múmkin', verbose_name='Mazmunı (Qaraqalpaqsha)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infopage',
            name='content_uz',
            field=models.TextField(default=1, help_text='HTML formatda yozish mumkin', verbose_name="Mazmuni (O'zbekcha)"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='infopage',
            name='key',
            field=models.CharField(help_text='Mısalı: about, support', max_length=50, unique=True, verbose_name='Kilt sóz'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='chat_id',
            field=models.BigIntegerField(unique=True, verbose_name='Chat ID'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Dizimnen ótken sáne'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Atı'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktiv'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='is_blocked',
            field=models.BooleanField(default=False, verbose_name='Bloklanǵan'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='last_activity',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Sońǵı aktivlik'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Familiyası'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Jańalanǵan sáne'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='userstate',
            name='current_state',
            field=models.CharField(default='start', max_length=50, verbose_name='Házirgi jaǵdayı'),
        ),
        migrations.AlterField(
            model_name='userstate',
            name='state_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Jaǵday maǵlıwmatları'),
        ),
        migrations.AlterField(
            model_name='userstate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Jańalandı'),
        ),
        migrations.AlterField(
            model_name='userstate',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='bot.telegramuser', verbose_name='Paydalanıwshı'),
        ),
    ]
