# Generated by Django 4.2.7 on 2025-08-22 23:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_alter_infopage_options_alter_telegramuser_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infopage',
            options={'verbose_name': 'Информационная страница', 'verbose_name_plural': 'Информационные страницы'},
        ),
        migrations.AlterModelOptions(
            name='telegramuser',
            options={'ordering': ['-created_at'], 'verbose_name': 'Пользователь Telegram', 'verbose_name_plural': 'Пользователи Telegram'},
        ),
        migrations.AlterModelOptions(
            name='userstate',
            options={'verbose_name': 'Состояние пользователя', 'verbose_name_plural': 'Состояния пользователей'},
        ),
        migrations.AlterField(
            model_name='infopage',
            name='content_qr',
            field=models.TextField(help_text='Можно использовать HTML-теги', verbose_name='Содержимое (Каракалпакский)'),
        ),
        migrations.AlterField(
            model_name='infopage',
            name='content_uz',
            field=models.TextField(help_text='Можно использовать HTML-теги', verbose_name='Содержимое (Узбекский)'),
        ),
        migrations.AlterField(
            model_name='infopage',
            name='key',
            field=models.CharField(help_text='Например: about, support', max_length=50, unique=True, verbose_name='Ключ'),
        ),
        migrations.AlterField(
            model_name='infopage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='is_blocked',
            field=models.BooleanField(default=False, verbose_name='Заблокирован'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='language',
            field=models.CharField(blank=True, choices=[('qr', 'Qaraqalpaq'), ('uz', 'Uzbek')], max_length=2, null=True, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='last_activity',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Последняя активность'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='userstate',
            name='current_state',
            field=models.CharField(default='start', max_length=50, verbose_name='Текущее состояние'),
        ),
        migrations.AlterField(
            model_name='userstate',
            name='state_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Данные состояния'),
        ),
        migrations.AlterField(
            model_name='userstate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='userstate',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='bot.telegramuser', verbose_name='Пользователь'),
        ),
    ]
